# This docker-compose.yml file tells Docker to do the following:
#  * Pull the image we uploaded in step 2 from the registry.
#  * Run 5 instances of that image as a service called web, limiting each one to use, at most, 10% of the CPU (across all cores), and 50MB of RAM.
#  * Immediately restart containers if one fails.
#  * Map port 80 on the host to web’s port 80.
#  * Instruct web’s containers to share port 80 via a load-balanced network called webnet. (Internally, the containers themselves will publish to web’s port 80 at an ephemeral port.)
#  * Define the webnet network with the default settings (which is a load-balanced overlay network).

version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: wawanco/get-started:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
